language: rust
rust:
  - stable
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose --all
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --package mentat_tx_parser
    fi