language: rust
# We use OSX so that we can get a reasonably up to date version of SQLCipher.
# (The version in Travis's default Ubuntu Trusty is much too old).
os: osx
before_install:
  - brew install sqlcipher --with-fts
rust:
  - 1.25.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
jobs:
  include:
    - stage: "Test iOS"
      rust: 1.25.0
      script: ./scripts/install-ios.sh
      script: ./scripts/test-ios.sh
    - stage: "Docs"
      rust: 1.25.0
      script: ./scripts/cargo-doc.sh
script:
  - cargo test --verbose --all
  - cargo test --features edn/serde_support --verbose --all
  # We can't pick individual features out with `cargo test --all` (At the time of this writing, this
  # works but does the wrong thing because of a bug in cargo, but its fix will be to disallow doing
  # this all-together, see https://github.com/rust-lang/cargo/issues/5364 for more information). To
  # work around this, we run individual tests for each subcrate individually.
  - |
    for manifest in $(find . -type f -name Cargo.toml); do
      cargo test --manifest-path $manifest --verbose --no-default-features --features sqlcipher
    done
cache: cargo
